#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" File automatically generated by Ezreq """
def print_ezreq(var):
    try:
        print(var.text)
    except AttributeError:
        print(var)

import requests

title = requests.get("https://example.org")
pipe_tmp = title
pipe_tmp = pipe_tmp.text.split("<title>")[1].split("</title>")[0]
print_ezreq(pipe_tmp)
pipe_tmp = requests.get("https://stallman.org")
print_ezreq(pipe_tmp)
print_ezreq(title)
title = pipe_tmp
END2 = pipe_tmp

exit(0)
