#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" File automatically generated by Ezreq """
def print_ezreq(var):
    try:
        print(var.text)
    except AttributeError:
        print(var)

import requests

web = requests.get("https://example.org")
title = web.text.split("<title>")[1].split("</title>")[0]
print_ezreq(title)
ref = web.text.split("<a href=\"")[1].split("\">")[0]
print_ezreq(ref)

exit(0)
